import { useState } from 'react';

function Modal({ title, onClose, children }) {
  return (
    <div style={{
      position: 'fixed', top: 0, left: 0, right: 0, bottom: 0,
      background: 'rgba(7,7,14,0.92)', backdropFilter: 'blur(6px)',
      zIndex: 1000, display: 'flex', alignItems: 'center', justifyContent: 'center',
      padding: 20,
    }} onClick={onClose}>
      <div style={{
        background: '#0f0f1a', border: '1px solid #2a2a40',
        padding: 32, maxWidth: 680, width: '100%', maxHeight: '85vh',
        overflowY: 'auto', position: 'relative',
      }} onClick={e => e.stopPropagation()}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 }}>
          <div style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: 28, color: '#ffaa00', letterSpacing: '0.05em' }}>
            {title}
          </div>
          <button onClick={onClose} style={{
            background: 'none', border: 'none', cursor: 'pointer',
            color: '#b0c0dd', fontSize: 20, padding: '4px 8px', fontFamily: 'inherit',
          }}>✕</button>
        </div>
        <div style={{ fontSize: 13, color: '#d0d8f0', lineHeight: 1.8 }}>
          {children}
        </div>
      </div>
    </div>
  );
}

function Section({ title, children }) {
  return (
    <div style={{ marginBottom: 24 }}>
      <div style={{ fontSize: 13, fontWeight: 700, color: '#ffaa00', marginBottom: 8,
        letterSpacing: '0.1em', textTransform: 'uppercase' }}>{title}</div>
      {children}
    </div>
  );
}

function P({ children }) {
  return <p style={{ margin: '0 0 10px', color: '#d0d8f0' }}>{children}</p>;
}

// ── Terms of Service ──────────────────────────────────────────────────────────

export function TermsModal({ onClose }) {
  return (
    <Modal title="Terms of Service" onClose={onClose}>
      <div style={{ fontSize: 11, color: '#7788aa', marginBottom: 20 }}>Last updated: March 2026</div>

      <Section title="1. Acceptance of Terms">
        <P>By accessing or using QuAInt Signal ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</P>
      </Section>

      <Section title="2. Not Financial Advice">
        <P>QuAInt Signal is an educational and analytical tool only. Nothing on this platform constitutes financial advice, investment advice, trading advice, or a recommendation to buy or sell any security, options contract, or other financial instrument.</P>
        <P>All signals, analyses, price targets, and recommendations generated by our AI are for informational purposes only. You should always conduct your own research and consult a licensed financial advisor before making any investment decisions.</P>
        <P><strong style={{ color: '#ff4444' }}>Trading involves significant risk. You may lose your entire investment. Past performance is not indicative of future results.</strong></P>
      </Section>

      <Section title="3. Use of the Service">
        <P>You must be 18 years of age or older to use this Service. You agree to use the Service only for lawful purposes and in accordance with these Terms.</P>
        <P>You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.</P>
      </Section>

      <Section title="4. Subscriptions and Payments">
        <P>QuAInt Signal offers a free tier with limited daily usage and a Pro subscription at $5 per month. Subscription fees are billed monthly and are non-refundable except as required by law.</P>
        <P>You may cancel your subscription at any time through your account settings. Cancellation takes effect at the end of the current billing period.</P>
        <P>We reserve the right to change subscription pricing with 30 days notice to active subscribers.</P>
      </Section>

      <Section title="5. Intellectual Property">
        <P>All content, features, and functionality of QuAInt Signal — including but not limited to AI prompts, analysis algorithms, trade signal logic, and user interface — are the exclusive property of QuAInt Signal and are protected by applicable intellectual property laws.</P>
      </Section>

      <Section title="6. Limitation of Liability">
        <P>To the maximum extent permitted by law, QuAInt Signal shall not be liable for any direct, indirect, incidental, special, or consequential damages arising from your use of the Service, including any trading losses incurred based on signals or analyses provided.</P>
      </Section>

      <Section title="7. Data and Privacy">
        <P>Your use of the Service is also governed by our Privacy Policy, which is incorporated into these Terms by reference.</P>
      </Section>

      <Section title="8. Modifications">
        <P>We reserve the right to modify these Terms at any time. Continued use of the Service after changes constitutes acceptance of the updated Terms.</P>
      </Section>

      <Section title="9. Contact">
        <P>For questions about these Terms, contact us at legal@quaint-signal.tech</P>
      </Section>
    </Modal>
  );
}

// ── Privacy Policy ────────────────────────────────────────────────────────────

export function PrivacyModal({ onClose }) {
  return (
    <Modal title="Privacy Policy" onClose={onClose}>
      <div style={{ fontSize: 11, color: '#7788aa', marginBottom: 20 }}>Last updated: March 2026</div>

      <Section title="1. Information We Collect">
        <P><strong>Account information:</strong> When you sign up via Clerk, we collect your name and email address.</P>
        <P><strong>Usage data:</strong> We track the number of scans and options analyses you run per day to enforce usage limits.</P>
        <P><strong>Payment information:</strong> Payments are processed by Stripe. We do not store your credit card details — only a Stripe customer ID and subscription status.</P>
        <P><strong>Analytics:</strong> We use Google Analytics (G-4LKYVR1S23) to understand how users interact with the app. This collects anonymized usage data including page views and session duration.</P>
      </Section>

      <Section title="2. How We Use Your Information">
        <P>We use your information to provide and improve the Service, manage your subscription, enforce usage limits, and communicate with you about your account.</P>
        <P>We do not sell, rent, or share your personal information with third parties for marketing purposes.</P>
      </Section>

      <Section title="3. Data Storage">
        <P>Account and usage data is stored in Supabase (PostgreSQL). Authentication is handled by Clerk. All data is encrypted at rest and in transit.</P>
      </Section>

      <Section title="4. Third-Party Services">
        <P>We use the following third-party services: Clerk (authentication), Stripe (payments), Supabase (database), Google Analytics (analytics), Anthropic Claude (AI analysis), Tradier (market data), and Polygon (market data).</P>
        <P>Each of these services has their own privacy policies governing the data they collect.</P>
      </Section>

      <Section title="5. Cookies">
        <P>We use cookies for authentication (Clerk) and analytics (Google Analytics). You can disable cookies in your browser settings, though this may affect functionality.</P>
      </Section>

      <Section title="6. Your Rights">
        <P>You may request access to, correction of, or deletion of your personal data by contacting us at privacy@quaint-signal.tech. We will respond within 30 days.</P>
      </Section>

      <Section title="7. Children's Privacy">
        <P>The Service is not directed to children under 18. We do not knowingly collect personal information from children under 18.</P>
      </Section>

      <Section title="8. Changes to This Policy">
        <P>We may update this Privacy Policy from time to time. We will notify you of significant changes via email or a prominent notice in the app.</P>
      </Section>

      <Section title="9. Contact">
        <P>For privacy-related questions, contact us at privacy@quaint-signal.tech</P>
      </Section>
    </Modal>
  );
}

// ── About ─────────────────────────────────────────────────────────────────────

export function AboutModal({ onClose }) {
  return (
    <Modal title="About QuAInt Signal" onClose={onClose}>
      <div style={{ textAlign: 'center', marginBottom: 28 }}>
        <div style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: 48, lineHeight: 0.9, marginBottom: 12 }}>
          <span style={{ color: '#ffaa00' }}>QU</span>
          <span style={{ color: '#00ff88' }}>AI</span>
          <span style={{ color: '#ffaa00' }}>NT SIGNAL</span>
        </div>
        <div style={{ fontSize: 12, color: '#7788aa', letterSpacing: '0.2em' }}>
          AI-POWERED MARKET INTELLIGENCE
        </div>
      </div>

      <Section title="What is QuAInt Signal?">
        <P>QuAInt Signal is an AI-powered investing platform built on Claude AI by Anthropic. We combine real-time market data, technical analysis, options flow, and global macro context to generate actionable trade signals for stocks and options.</P>
        <P>Every signal includes an exact entry price, price target, and stop loss — not vague directional bias. Our AI analyzes RSI, MACD, Bollinger Bands, ATR, Support/Resistance levels, IV skew, unusual options volume, earnings proximity, and 15+ global macro indicators before generating any recommendation.</P>
      </Section>

      <Section title="Our Mission">
        <P>We built QuAInt Signal out of frustration with expensive, complex trading tools that assume you already know everything. We wanted to give individual investors access to institutional-grade analysis without the six-figure subscription — combining the power of AI with real-time market data in a tool anyone can use.</P>
      </Section>

      <Section title="Technology">
        <P>QuAInt Signal is powered by Anthropic's Claude Sonnet AI model, real-time options data from Tradier, market data from Polygon, and a custom indicator suite including MACD, Bollinger Bands, Stochastic RSI, ATR-based stop sizing, and pivot-based Support/Resistance levels.</P>
      </Section>

      <Section title="Important Disclaimer">
        <P style={{ color: '#ff4444' }}>QuAInt Signal is an educational and analytical tool only. Nothing on this platform constitutes financial advice. Trading involves significant risk and is not suitable for all investors. Always do your own research and consult a licensed financial advisor before trading.</P>
      </Section>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8, marginTop: 8 }}>
        {[
          { icon: '🤖', label: 'AI Engine',     value: 'Claude Sonnet by Anthropic' },
          { icon: '📈', label: 'Options Data',  value: 'Tradier — Real-time chains'  },
          { icon: '📊', label: 'Market Data',   value: 'Polygon — Global markets'    },
          { icon: '🔒', label: 'Auth',          value: 'Clerk — Secure login'        },
          { icon: '💾', label: 'Database',      value: 'Supabase — PostgreSQL'       },
          { icon: '💳', label: 'Payments',      value: 'Stripe — Secure checkout'    },
        ].map((item, i) => (
          <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 10,
            background: '#070710', padding: '10px 12px', borderRadius: 2,
            border: '1px solid #1e1e30' }}>
            <span style={{ fontSize: 16 }}>{item.icon}</span>
            <div>
              <div style={{ fontSize: 9, color: '#7788aa', letterSpacing: '0.1em' }}>{item.label}</div>
              <div style={{ fontSize: 11, color: '#e8e8f0', fontWeight: 600 }}>{item.value}</div>
            </div>
          </div>
        ))}
      </div>
    </Modal>
  );
}

// ── Contact ───────────────────────────────────────────────────────────────────

export function ContactModal({ onClose }) {
  return (
    <Modal title="Contact Us" onClose={onClose}>
      <P>We'd love to hear from you — whether it's a bug report, feature request, or general feedback.</P>

      <Section title="General Inquiries">
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          {[
            { icon: '📧', label: 'General',  value: 'hello@quaint-signal.tech'   },
            { icon: '🔒', label: 'Privacy',  value: 'privacy@quaint-signal.tech' },
            { icon: '⚖️', label: 'Legal',    value: 'legal@quaint-signal.tech'   },
            { icon: '💳', label: 'Billing',  value: 'billing@quaint-signal.tech' },
          ].map((item, i) => (
            <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 12,
              background: '#070710', padding: '12px 16px', border: '1px solid #1e1e30' }}>
              <span style={{ fontSize: 18 }}>{item.icon}</span>
              <div>
                <div style={{ fontSize: 10, color: '#7788aa', letterSpacing: '0.1em', marginBottom: 2 }}>{item.label}</div>
                <a href={`mailto:${item.value}`} style={{ fontSize: 13, color: '#ffaa00',
                  textDecoration: 'none', fontWeight: 600 }}>{item.value}</a>
              </div>
            </div>
          ))}
        </div>
      </Section>

      <Section title="Response Time">
        <P>We typically respond within 24-48 hours on business days.</P>
      </Section>

      <Section title="Bug Reports">
        <P>Found a bug? Please include your browser, device type, and steps to reproduce. Screenshots are always helpful.</P>
      </Section>

      <Section title="Feature Requests">
        <P>We actively build based on user feedback. If there's a feature you'd like to see, we want to hear about it.</P>
      </Section>

      <div style={{ marginTop: 24, padding: '16px', background: '#070710',
        border: '1px solid #ffaa0033', textAlign: 'center' }}>
        <div style={{ fontSize: 11, color: '#b0c0dd', marginBottom: 4 }}>Follow us for updates</div>
        <a href="https://twitter.com/QuAIntSignal" target="_blank" rel="noopener noreferrer"
          style={{ fontSize: 13, color: '#ffaa00', textDecoration: 'none', fontWeight: 700 }}>
          @QuAIntSignal on X/Twitter
        </a>
      </div>
    </Modal>
  );
}